name: Daily ingest and rebase

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v6
        with:
          ref: live-update-test
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase on main
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          pip-install: "requests"

      - name: Run ingest script
        id: ingest
        run: |
          python -m src.orchestrator --operation ingest --data-sources-path ./configs/latest_data_source.json

      - name: Commit and push if changes exist
        if: success()
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'Daily update commit'
          branch: live-update-test
          file_pattern: '*.db'
          push_options: '--force-with-lease'
          skip_push: false
          create_branch: false
